#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC36CDCB4DF00C68C (infra-root@openstack.org)
#
Name     : os-brick
Version  : 2.5.3
Release  : 27
URL      : http://tarballs.openstack.org/os-brick/os-brick-2.5.3.tar.gz
Source0  : http://tarballs.openstack.org/os-brick/os-brick-2.5.3.tar.gz
Source99 : http://tarballs.openstack.org/os-brick/os-brick-2.5.3.tar.gz.asc
Summary  : OpenStack Cinder brick library for managing local volume attaches
Group    : Development/Tools
License  : Apache-2.0
Requires: os-brick-python3
Requires: os-brick-data
Requires: os-brick-license
Requires: os-brick-python
Requires: Babel
Requires: eventlet
Requires: os-win
Requires: oslo.concurrency
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.service
Requires: oslo.utils
Requires: pbr
Requires: requests
Requires: retrying
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools
Patch1: 0001-move-etc-os-brick-rootwrap.d-os-brick.filters-to-sta.patch

%description
Team and repository tags
        ========================

%package data
Summary: data components for the os-brick package.
Group: Data

%description data
data components for the os-brick package.


%package license
Summary: license components for the os-brick package.
Group: Default

%description license
license components for the os-brick package.


%package python
Summary: python components for the os-brick package.
Group: Default
Requires: os-brick-python3

%description python
python components for the os-brick package.


%package python3
Summary: python3 components for the os-brick package.
Group: Default
Requires: python3-core

%description python3
python3 components for the os-brick package.


%prep
%setup -q -n os-brick-2.5.3
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532270391
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/os-brick
cp LICENSE %{buildroot}/usr/share/doc/os-brick/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/defaults/os-brick/rootwrap.d/os-brick.filters

%files license
%defattr(-,root,root,-)
/usr/share/doc/os-brick/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
